require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3

Style/Documentation:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20