---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/patient-account/additional-data":
    get:
      summary: list additional_infos
      tags:
      - Additional Information
      responses:
        '200':
          description: successful
    post:
      summary: create additional_info
      tags:
      - Additional Information
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  default: Must be 'address' or 'work'
                address_type:
                  type: string
                  default: Основна
                settlement:
                  type: string
                  default: Черкаси
                house:
                  type: string
                  default: '1'
                apartments:
                  type: string
                  default: '1'
                work_type:
                  type: string
                  default: Основна
                place:
                  type: string
                  default: GeekHub
                position:
                  type: string
                  default: Студент
    put:
      summary: update additional_info
      tags:
      - Additional Information
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  default: Must be 'address' or 'work'
                address_type:
                  type: string
                  default: Основна
                settlement:
                  type: string
                  default: Черкаси
                house:
                  type: string
                  default: '1'
                apartments:
                  type: string
                  default: '1'
                work_type:
                  type: string
                  default: Основна
                place:
                  type: string
                  default: GeekHub
                position:
                  type: string
                  default: Студент
    delete:
      summary: delete additional_info
      tags:
      - Additional Information
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  default: Must be 'address' or 'work'
  "/api/v1/edit_doctor":
    patch:
      summary: Update doctors params
      tags:
      - Doctors cabinet
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                second_email:
                  type: string
                second_phone:
                  type: integer
                description:
                  type: string
                price:
                  type: integer
              required:
              - second_email
              - second_phone
              - description
              - price
        description: Doctors params to update
  "/api/v1/personal_info":
    get:
      summary: Returns personal information about the doctor
      tags:
      - Doctors cabinet
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: returns personal information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    full_name:
                      type: string
                    email:
                      type: string
                    second_email:
                      type: string
                    phone:
                      type: integer
                    second_phone:
                      type: integer
                    description:
                      type: string
                  required:
                  - full_name
                  - email
                  - second_email
                  - second_phone
                  - description
        '422':
          description: Unprocessable_entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/professional_info":
    get:
      summary: Returns professional information about the doctor
      tags:
      - Doctors cabinet
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: returns professional information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    price:
                      type: integer
                    position:
                      type: string
                    hospital_city:
                      type: string
                    hospital_region:
                      type: string
                    hospital_address:
                      type: string
                    hospital_name:
                      type: string
                  required:
                  - price
                  - position
                  - hospital_city
                  - hospital_region
                  - hospital_address
                  - hospital_name
  "/api/v1/doctors":
    get:
      summary: list doctors
      tags:
      - Doctors
      responses:
        '200':
          description: successful
  "/api/v1/head_doctors":
    get:
      summary: Retrieves a list of doctors associated with the head doctor
      tags:
      - Head Doctors
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: returns a list of doctors
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    email:
                      type: string
                    phone:
                      type: integer
                    birthday:
                      type: string
                    position:
                      type: string
                    rating:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    head_doctor_id:
                      type: integer
                    hospital_id:
                      type: integer
                  required:
                  - id
                  - name
                  - surname
                  - email
                  - phone
                  - birthday
                  - position
                  - rating
                  - created_at
                  - updated_at
                  - head_doctor_id
                  - hospital_id
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/head_doctors/create_doctor":
    post:
      summary: Creates a doctor
      tags:
      - Head Doctors
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '201':
          description: returns the newly created doctor
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                phone:
                  type: integer
                birthday:
                  type: string
                position:
                  type: string
              required:
              - name
              - surname
              - email
              - phone
              - birthday
              - position
              - hospital_id
              - password
              - password_confirmation
  "/api/v1/head_doctors/create_hospital":
    post:
      summary: Creates a hospital
      tags:
      - Head Doctors
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '201':
          description: returns the newly created hospital
        '422':
          description: returns an error message if hospital cannot be created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
                city:
                  type: string
                region:
                  type: string
              required:
              - name
              - address
              - city
              - region
  "/api/v1/head_doctors/{id}/delete":
    delete:
      summary: Deletes a doctor by id
      tags:
      - Head Doctors
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        description: Doctor ID
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: doctor deleted
        '404':
          description: doctor not found
  "/api/v1/forgot":
    post:
      summary: Sends an email to reset the user's password
      tags:
      - Passwords
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                user_type:
                  type: string
              required:
              - email
              - user_type
        description: The user's email address
  "/api/v1/reset":
    post:
      summary: Resets the user's password
      tags:
      - Passwords
      parameters:
      - name: token
        in: query
        description: The password reset token generated for the user
        required: true
        schema:
          type: string
      - name: user_type
        in: query
        description: The user's type
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
              - password
        description: The new password for the user
  "/api/v1/patient-account/personal-information":
    get:
      summary: list personal_infos
      tags:
      - Personal Information
      responses:
        '200':
          description: successful
    post:
      summary: create personal_info
      tags:
      - Personal Information
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                document_type:
                  type: string
                  default: Must be 'Passport' or 'IdCard'
                series:
                  type: string
                  default: Dont use for IdCard
                number:
                  type: string
                  default: '1111'
                issued_by:
                  type: string
                  default: '1111'
                date:
                  type: string
                  default: 12.04.2023
    put:
      summary: update personal_info
      tags:
      - Personal Information
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  default: Must be 'patient_info' or 'document'
                name:
                  type: string
                  default: Юзер
                surname:
                  type: string
                  default: Юзеренко
                fathername:
                  type: string
                  default: Юзеренкович
                email:
                  type: string
                  default: user@test.rb
                phone:
                  type: string
                  default: "+380000000000"
                birthday:
                  type: string
                  default: 05.11.2003
                tin:
                  type: string
                  default: '1111111111'
                sex:
                  type: string
                  default: "'nothing', 'male' or 'female'"
                series:
                  type: string
                  default: Use for Passport
                number:
                  type: string
                  default: '1111'
                issued_by:
                  type: string
                  default: '1111'
                date:
                  type: string
                  default: 12.04.2023
    delete:
      summary: delete personal_info
      tags:
      - Personal Information
      responses:
        '200':
          description: successful
  "/api/v1/signup":
    post:
      summary: Sends an email to register user
      tags:
      - Signup
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
        description: The user's email and password
  "/api/v1/confirmation":
    post:
      summary: Confirmation user's email and input other data
      tags:
      - Signup
      parameters:
      - name: token
        in: query
        description: The confirm reset token generated for the patient
        required: true
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                birthday:
                  type: string
                  format: datetime
                name:
                  type: string
                second_name:
                  type: string
                surname:
                  type: string
                phone:
                  type: string
                  format: bigint
              required:
              - birthday
              - name
              - surname
              - phone
        description: Patient data
  "/api/v1/search":
    get:
      summary: Search for hospitals or doctors
      tags:
      - Search
      parameters:
      - name: query
        in: query
        description: Search query for hospital or doctor
        required: true
        schema:
          type: string
      - name: region
        in: query
        description: Region filter
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Hospitals and doctors found
          content:
            application/json:
              schema:
                type: object
                properties:
                  hospitals:
                    type: array
                  doctors:
                    type: array
        '422':
          description: Invalid search query
  "/api/v1/login":
    post:
      summary: create session
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                user_type:
                  type: string
              required:
              - email
              - password
              - user_type
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
- url: http://{behealthtHost}
  variables:
    behealthHost:
      default: 64.226.64.5
- url: http://{behealth_host}
  variables:
    behealth_host:
      default: 161.35.210.52
- url: http://{staging_host}
  variables:
    staging_host:
      default: ''
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: "{token}"
