---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/doctors":
    get:
      summary: list doctors
      tags:
      - Doctors
      responses:
        '200':
          description: successful
  "/api/v1/forgot":
    post:
      summary: Sends an email to reset the user's password
      tags:
      - Passwords
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                user_type:
                  type: string
              required:
              - email
              - user_type
        description: The user's email address
  "/api/v1/reset":
    post:
      summary: Resets the user's password
      tags:
      - Passwords
      parameters:
      - name: token
        in: query
        description: The password reset token generated for the user
        required: true
        schema:
          type: string
      - name: user_type
        in: query
        description: The user's type
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
              - password
        description: The new password for the user
  "/api/v1/signup":
    post:
      summary: Sends an email to register user
      tags:
      - Signup
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
        description: The user's email and password
  "/api/v1/confirmation":
    post:
      summary: Confirmation user's email and input other data
      tags:
      - Signup
      parameters:
      - name: token
        in: query
        description: The confirm reset token generated for the patient
        required: true
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                birthday:
                  type: string
                  format: datetime
                name:
                  type: string
                surname:
                  type: string
                phone:
                  type: string
                  format: bigint
              required:
              - birthday
              - name
              - surname
              - phone
        description: Patient data
  "/api/v1/login":
    post:
      summary: create session
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                user_type:
                  type: string
              required:
              - email
              - password
              - user_type
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{behealth_host}
  variables:
    behealth_host:
      default: 161.35.210.52
- url: https://{staging_host}
  variables:
    staging_host:
      default: ''
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      description: "{token}"
